export default {
  $window: window,
  $document: document,
  $html: document.documentElement,
  $body: document.body,
  $bannerSlider: document.querySelector('.banner-slider'),
  $reviewSlider: document.querySelector('.reviews-slider'),
  $anchors: document.querySelectorAll('.nav__link'),
  $navHead: document.querySelectorAll('.header__nav'),
  $headerFix: document.querySelectorAll('.header'),
  $workLink: document.querySelectorAll('.works-nav__link'),
  $burger: document.querySelector('.burger'),
  $navClose: document.querySelector('.nav__close'),
  $nav: document.querySelector('.nav'),
}
